- name:             Madx Deposit Wallet
  blockchain_key:   madx-testnet
  currency_id:      madx
  # Address where deposits will be collected to.
  address:          'Qc2BM7gp8mKgJPPxLAadLAHteNQwhFwwuf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             deposit    # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1          # Number of signatures required for performing withdraw.
  max_balance:      0.0
  status:           active
  gateway:          madxd  # Gateway client name.
  settings:
    #
    # Madxd gateway client settings.
    uri:          http://user:password@127.0.0.1:19332

- name:             Madx Hot Wallet
  blockchain_key:   madx-testnet
  currency_id:      madx
  # Address where deposits will be collected to.
  address:          'Qc2BM7gp8mKgJPPxLAadLAHteNQwhFwwuf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             hot     # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1       # Number of signatures required for performing withdraw.
  max_balance:      5.0
  status:           active
  gateway:          madxd   # Gateway client name.
  settings:
    #
    # Madxd gateway client settings.
    uri:          http://user:password@127.0.0.1:19332

- name:             Madx Warm Wallet
  blockchain_key:   madx-testnet
  currency_id:      madx
  # Address where deposits will be collected to.
  address:          'Qc2BM7gp8mKgJPPxLAadLAHteNQwhFwwuf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             warm    # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1       # Number of signatures required for performing withdraw.
  max_balance:      50.0
  status:           active
  gateway:          madxd   # Gateway client name.
  settings:
    #
    # Madxd gateway client settings.
    uri:          http://user:password@127.0.0.1:19332
